version: '3.7'

services:
  bookshelf-db:
    image: postgres
    container_name: bookshelf-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: bookshelf-app
    depends_on:
      - bookshelf-db
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://bookshelf-db:5432/postgres
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres