version: '3.7'

services:
  bookshelf-db:
    image: postgres
    container_name: bookshelf-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: bookshelf-app
    depends_on:
      - bookshelf-db
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://bookshelf-db:5432/postgres
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4jBookshelf
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=512M
      - NEO4J_dbms_memory_pagecache_size=512M
    volumes:
      - ./data:/data