version: '3.7'

services:
  bookshelf-db:
    image: postgres
    container_name: bookshelf-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"